# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"

  config.vm.provision :shell, path: "bootstrap.sh"
  # Add link to firmware folder
  config.vm.synced_folder "../../", "/ioio"
end
